### ISSUE TITLE
Use `require` rather than `includes`

### ISSUE THREAD

**Issue by necolas** [okor/justice#22]
You can use webpack to build this as a UMD module.

**Comment by okor** [comment]
So, I deliberately avoided all the module loading techniques because they have yet to be settled. If anything, I'd be willing to do ES6 transpiled to ES5. I'm very open to PR's

https://github.com/babel/grunt-babel
https://github.com/babel/babel

But I agree that the current way in which Justice is built is ... weird and non-standard.

**Comment by necolas** [comment]
Yeah I thought I'd quickly port to es6 / commonjs and use webpack to compile to a UMD library, but it was hard to trace the implicit dependencies and I didn't have time.
