### ISSUE TITLE
bookmarklet

### ISSUE THREAD

**Issue by dominikwilkowski** [okor/justice#24]
:+1:  for the bookmarklet in your roadmap!
That would proof very handy!!

**Comment by okor** [comment]
I generally dislike bookmarklets because the browser will try to string match on your bookmarks which can freeze the primary text input field for search (in Chrome at least) when you have a long bookmarklet. They are implemented in a very half ass way.

But, sigh. I did actually have a bookmarklet on the project page for a while. I'll try to get a repeatable grunt task down build building it and put it back up there.

**Comment by x1024** [comment]
+1 for bookmarklets. Any performance work I do starts with an estimate of what needs to be done. This is usually done *before* getting write access to the client's servers, so a bookmarklet is the only viable solution (that doesn't involve copy-pasting huge amounts of code in the console).

**Comment by okor** [comment]
@x1024 @dominikwilkowski I've added a bookmarklet to the demo page: http://okor.github.io/justice/

I just manually created it but will try to get it into the build process soon so it's always fresh.

**Comment by dominikwilkowski** [comment]
:+1:

**Comment by dominikwilkowski** [comment]
We can close this, no?
